Added bitwise and or xor support
CrossGL/crosstl pull request #126
Opened 2024-09-02 11:05 UTC by ashwith2427

2024-09-02 11:40 UTC, NripeshN requested changes

2024-09-02 11:40 UTC, NripeshN commented on crosstl/src/backend/Opengl/OpenglLexer.py
> +    # ("ASSIGN_BINOPOR", r"\|="),
Hi,
Why are we commenting these out?

2024-09-02 12:41 UTC, ashwith2427 commented on crosstl/src/backend/Opengl/OpenglLexer.py
>      ("MINUS", r"-"),
Hi Nripesh,
I have deleted those comments inside Lexer

2024-09-02 16:59 UTC, ashwith2427 reviewed
I have also added assignment OR,XOR,AND and fixed the other assignment operations.

2024-09-03 04:28 UTC, ashwith2427 reviewed
Fixed a bug with assign add

2024-09-04 05:39 UTC, NripeshN requested changes

2024-09-04 05:39 UTC, NripeshN commented on crosstl/src/backend/Opengl/OpenglParser.py
> +            # right = self.parse_additive()
Another comment that we can remove, small question though:

- Are we replacing `parse_additive` functionality in `parse_binop`
- If yes are we using `parse_additive` function anywhere else?
- If not then we can delete the function def itself

2024-09-04 05:51 UTC, ashwith2427 commented on crosstl/src/backend/Opengl/OpenglParser.py
> +            # right = self.parse_additive()
We are using parse_additive inside binop. Since additive and all other operations have higher precedence than bitwise.

Let's say we have 
int a = 1|4+3

Then first 4+3 will get reduced and then the or operation is performed exactly like what we have done for multiplication, we call it from additive function.

2024-09-04 06:06 UTC, NripeshN commented
@ashwith2427 
Can we make sure we add tests for this in `tests/test_backend/test_opengl/test_parser.py`

2024-09-04 06:09 UTC, ashwith2427 commented
> @ashwith2427 Can we make sure we add tests for this in `tests/test_backend/test_opengl/test_parser.py`

Yeah sure I will add them.

2024-09-04 06:53 UTC, ashwith2427 reviewed
Added tests for assign add,mul,div,or,and,xor and also fixed the problem with comments.

2024-09-04 07:02 UTC, NripeshN approved these changes
LGTM!!
@samthakur587 
Please do a final review of the PR and merge it😁

2024-09-05 06:19 UTC, samthakur587 requested changes
hii @ashwith2427 changes is you made looking great to me i suggested few changes can you please add those changes. and also can you please change the codegen file also for this changes are generating the correct crossgl code . also we have different test files for the lexer , parser and codegen can you add test in all this file not just at parser file.

2024-09-05 06:19 UTC, samthakur587 commented on crosstl/src/backend/Opengl/OpenglLexer.py
>      ("EQUAL", r"=="),
hii @ashwith2427 can you please change the name of tokens to be like 

```bash

("ASSIGN_AND", r"&="),
    ("ASSIGN_OR", r"\|="),
    ("ASSIGN_XOR", r"\^="),
```

2024-09-05 06:19 UTC, samthakur587 commented on crosstl/src/backend/Opengl/OpenglLexer.py
> +    ("BINOPXOR", r"\^"),
also for this Token name to be 
```bash
("BITWISE_SHIFT_LEFT", r"<<"),
 ("BITWISE_SHIFT_RIGHT", r">>"),
("BITWISE_AND", r"&"),
    ("BITWISE_OR", r"\|"),
    ("BITWISE_XOR", r"\^"),
```

2024-09-05 06:22 UTC, samthakur587 commented
hii @ashwith2427 can you create a issue for each token you are adding support on which file lexer , parser , codegen so we can have track on this that this task is completed . i'll assign these issue to you once you created that issue .

2024-09-05 06:24 UTC, ashwith2427 commented
Ok @samthakur587

2024-09-05 06:36 UTC, ashwith2427 commented
I have added the issue @samthakur587

2024-09-05 09:51 UTC, ashwith2427 reviewed
@samthakur587 I have fixed the code.

2024-09-06 11:23 UTC, samthakur587 commented
hii @ashwith2427 can you please edit your PR description and mention there the issue in which you are working on.

2024-09-06 11:43 UTC, ashwith2427 commented
@samthakur587 I have updated the PR

2024-09-09 07:15 UTC, samthakur587 requested changes

2024-09-09 07:15 UTC, samthakur587 commented on tests/test_backend/test_opengl/test_parser.py
> +        #version 450
why is this unit_test needed ? you only have to add the tests for you each token or issue you are working on like it is correct for `bitwise` but you also have to add the test like test_double , test_uint etc as a different function .

2024-09-09 07:15 UTC, samthakur587 commented on crosstl/src/backend/Opengl/openglCrossglCodegen.py
>          }
also add tests for codegen file also the changes you have mode.

2024-09-09 07:15 UTC, samthakur587 commented on crosstl/src/backend/Opengl/OpenglParser.py
> +                if op == "ASSIGN_ADD":
this will not work like that checking for each operator just use the assignment node and save the operator in the node. or use binaryopnode

2024-09-09 07:15 UTC, samthakur587 commented on crosstl/src/backend/Opengl/OpenglParser.py
> +            if type_name in ["int", "float", "unsigned int", "double"]:
unsigned int (opengl) -> uint (crossgl )

2024-09-09 08:01 UTC, ashwith2427 commented on crosstl/src/backend/Opengl/OpenglParser.py
> +            if type_name in ["int", "float", "unsigned int", "double"]:
yeah thats true iam mapping the types in codegen file. you can test it.

2024-09-09 08:10 UTC, ashwith2427 commented on crosstl/src/backend/Opengl/OpenglParser.py
> +                if op == "ASSIGN_ADD":
But if i do striaght away there is a problem with braces in the expression once try it with int x += (2*4)+(4*5)
the end result is 
x+=2*4+4*5
The precedence is eaten.

2024-09-09 08:43 UTC, ashwith2427 commented
Hey @samthakur587 I have updated the code

2024-09-11 05:40 UTC, samthakur587 requested changes
hii @ashwith2427 great work till now we are very close to merge this PR. can you please made some changes that i have suggested .

2024-09-11 05:40 UTC, samthakur587 commented on crosstl/src/backend/Opengl/OpenglLexer.py
> +    ("BITWISE_AND", r"&"),
for these two token `BITWISE_SHIFT_LEFT` , `BITWISE_SHIFT_RIGHT` you havn't done anything as i have seen why have you added these in laxer token. either you can add support also for these two tokens in parser and codegen or you can just remove these token from here so that anyone else can work on this.

2024-09-11 05:40 UTC, samthakur587 commented on tests/test_backend/test_opengl/test_lexer.py
> +        pytest.fail("Bitwise operation failed")
also can you please add tests for `unsigned int` and `double` token also here

2024-09-11 11:33 UTC, ashwith2427 commented
I have updated the code @samthakur587

2024-09-13 09:43 UTC, samthakur587 requested changes

2024-09-13 09:43 UTC, samthakur587 commented on crosstl/src/backend/Opengl/openglCrossglCodegen.py
> +            "ASSIGN_AND": "&",
why here the bitwise_and and assign_and same and same thing for bitwise_or ,bitwise_and . the assign_and should be like &= and assign_or |= .

2024-09-13 11:10 UTC, ashwith2427 commented on crosstl/src/backend/Opengl/openglCrossglCodegen.py
> +            "ASSIGN_AND": "&",
Yeah in lexer it is &= and \= but when we map those we need to do & and then we assign right. Once can you check the result of assign.

2024-12-26 13:04 UTC, NripeshN commented
<!-- BOT_STATE: {} -->

2024-12-26 13:11 UTC, NripeshN commented
<!-- BOT_STATE: {} -->

2024-12-26 13:14 UTC, NripeshN commented
<!-- BOT_STATE: {} -->

2025-01-30 00:03 UTC, closed without merging