Added translator support for Modulus token
CrossGL/crosstl pull request #136
Opened 2024-09-05 10:39 UTC by vishalghige43

### PR Description
Added support for the modulus operator (```%```) and the assignment modulus operator (```%=```) in the CGL translator.

### Related Issue
Resolves #116 
Working on adding modulus support to the backend.

### Shader Sample
This is the ```PerlinNoise.cgl``` example code for testing the modulus operator (```%```) and assignment modulus operator (```%=```):

```crossgl
shader PerlinNoise {

    // Perlin Noise Function
    float perlinNoise(vec2 p) {
        return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
    }

    // Fragment Shader
    fragment {
        input vec2 vUV;
        output vec4 fragColor;

        void main() {
            float noise = perlinNoise(vUV);
            float height = noise * 10.0;
            vec3 color = vec3(height / 10.0, 1.0 - height / 10.0, 0.0);
            fragColor = vec4(color, 1.0);

            int color2 = 1200 % 10;       //MOD test
            color2 %= 10;                   //ASSIGN_MOD test
        }
    }
}
```

### Checklist
- [ ] Have you added the necessary tests?
- [x] Only modified the files mentioned in the related issue(s)?
- [ ] Are all tests passing?

2024-09-06 08:19 UTC, samthakur587 requested changes

2024-09-06 08:19 UTC, samthakur587 commented on examples/PerlinNoise.cgl
> +            color2 %= 10;                    //ASSIGN_MOD test
this is just a demo shader file do not change anything here . write tests only at `tests/test_translator/test_codegen/`

2024-09-06 13:35 UTC, vishalghige43 commented on crosstl/src/translator/codegen/directx_codegen.py
>              "LESS_EQUAL": "<=",
Ok, I'll make the changes and only include the modifications for the MOD operator in the PR

2024-09-06 13:37 UTC, vishalghige43 commented on examples/PerlinNoise.cgl
> +            color2 %= 10;                    //ASSIGN_MOD test
Got it! I won't make any changes to the demo shader file.
Thanks for the clarification.

2024-09-09 07:34 UTC, samthakur587 requested changes
add tests also for you changes

2024-09-09 07:34 UTC, samthakur587 commented on crosstl/src/translator/parser.py
>              "BITWISE_SHIFT_RIGHT",
why you removed the `Assign_MOD` no need to remove it your task it to just add `MOD` support at translator frontend.

2024-09-16 10:17 UTC, samthakur587 commented
hii @vishalghige43 can you please [fix](https://github.com/CrossGL/crosstl/actions/runs/10740449493/job/29788564314?pr=136#step:5:235) this and also solve the merge conflict .

2024-09-17 06:39 UTC, vishalghige43 commented
> hii @vishalghige43 can you please [fix](https://github.com/CrossGL/crosstl/actions/runs/10740449493/job/29788564314?pr=136#step:5:235) this and also solve the merge conflict .

ok,I'll complete it today.

2024-12-26 13:03 UTC, NripeshN commented
<!-- BOT_STATE: {} -->

2024-12-26 13:11 UTC, NripeshN commented
<!-- BOT_STATE: {} -->

2024-12-26 13:14 UTC, NripeshN commented
<!-- BOT_STATE: {} -->

2025-01-01 16:10 UTC, dheeraxspidey commented
@CrossGL-issue-bot assign me

2025-01-03 15:12 UTC, closed without merging