Feature/add translator support for assignment shift right
CrossGL/crosstl pull request #137
Opened 2024-09-05 15:29 UTC by shankkyy

## PR Description  
**Added support for the assignment right shift operator (`>>=`) in the CGL translator.**

## Related Issue  
Resolves **#118**  
This PR introduces support for the assignment right shift (`>>=`) operator, allowing for proper translation of this operator in shader code generation.

## Shader Sample  
Here’s an example shader code that demonstrates the usage of the assignment right shift (`>>=`) operator:

shader BitwiseShift {

    // Fragment Shader
    fragment {
        input vec2 vUV;
        output vec4 fragColor;

        void main() {
            int value = 1024;
            value >>= 2;  // ASSIGN_SHIFT_RIGHT test, shifting value right by 2 bits

            fragColor = vec4(float(value) / 1024.0, 0.0, 0.0, 1.0);
        }
    }
}

### Checklist
- [X] Have you added the necessary tests?
- [X] Only modified the files mentioned in the related issue(s)?
- [X] Are all tests passing?

2024-09-06 06:39 UTC, samthakur587 requested changes

2024-09-06 06:39 UTC, samthakur587 commented on examples/PerlinNoise.cgl
>          }
hii @shankkyy this is not the correct place to put your test and show what you have added . this is just the demo examples. you can write your tests on the `crosstl/tests/test_translator/test_codegen` .

2024-09-06 06:47 UTC, shankkyy commented on examples/PerlinNoise.cgl
>          }
ok sure I'll fix it

2024-09-06 06:55 UTC, shankkyy commented on examples/PerlinNoise.cgl
>          }
I removed the code from the examples file and tested the code in  crosstl/tests/test_translator/test_codegen this file

2024-09-06 08:21 UTC, samthakur587 reviewed
hii @shankkyy can you please add tests also for these changes

2024-09-16 10:21 UTC, samthakur587 commented
hii @shankkyy can you please fix the tests that are not passing and solve the merge conflict . ask me if you facing any difficulty in code .

2024-12-26 13:03 UTC, NripeshN commented
<!-- BOT_STATE: {} -->

2024-12-26 13:11 UTC, NripeshN commented
<!-- BOT_STATE: {} -->

2024-12-26 13:14 UTC, NripeshN commented
<!-- BOT_STATE: {} -->

2025-01-27 00:04 UTC, closed without merging