fix: added support for more complex statement decleration
CrossGL/crosstl pull request #38
Opened 2024-08-16 11:29 UTC by samthakur587

2024-08-17 14:22 UTC, NripeshN requested changes

2024-08-17 14:22 UTC, NripeshN commented on crosstl/src/translator/codegen/directx_codegen.py
> +        print(ast)
@samthakur587 
Is there a reason why we are adding this print statement?

2024-08-18 12:34 UTC, samthakur587 commented on crosstl/src/translator/codegen/directx_codegen.py
> +        print(ast)
it's for debugging i removed it

2024-08-18 16:37 UTC, vaatsalya123 commented
Lgtm! Awesome work Sam.

2024-08-18 16:38 UTC, vaatsalya123 approved these changes

2024-08-20 00:15 UTC, NripeshN approved these changes
LGTM!

2024-08-20 00:15 UTC, merged