Add parsing support for ASSIGN_SHIFT_RIGHT token (>>= operator)
CrossGL/crosstl pull request #95
Opened 2024-08-23 14:44 UTC by anshikavashistha

This PR addresses issue #82 by adding support for parsing the ASSIGN_SHIFT_RIGHT token (>>= operator) in the translator parser. This enhancement ensures that the parser correctly recognizes and processes expressions involving the >>= operator.

2024-08-23 14:45 UTC, anshikavashistha commented
@samthakur587 @NripeshN PTAL

2024-08-24 12:51 UTC, samthakur587 reviewed
hii @anshikavashistha  can you please solve the merge conflicts and assign issue your self before making the PR 😄  

i have assigned you for this issue .

2024-08-28 06:53 UTC, samthakur587 requested changes
hii @anshikavashistha can you make these changes i have requested .

2024-08-28 06:53 UTC, samthakur587 commented on crosstl/src/translator/lexer.py
>      ("LOGICAL_AND", r"&&"),
hii @anshikavashistha this task is required to changes in parser.py file at translator file which is located at `crosstl/src/translator/parser.py` . you can pull the latest changes the Token `ASSIGN_SHIFT_RIGHT` is already added .

2024-08-28 06:53 UTC, samthakur587 commented on tests/test_translator/test_parser.py
> +        pytest.fail(f"Failed to parse ASSIGN_SHIFT_RIGHT token: {e}")
the test is currently not passing bcz you havn't made any changes in parser.py file.after adding support for this Token at parser.py file then this test will pass.

2024-08-29 08:37 UTC, samthakur587 commented
hii @anshikavashistha can you please resolve the merge conflicts

2024-09-05 08:41 UTC, samthakur587 approved these changes
hii @anshikavashistha changes LGTM 🚀

2024-09-05 08:41 UTC, merged