Added Support for >>, <<, >>= and <<= Tokens
CrossGL/crosstl pull request #97
Opened 2024-08-23 17:19 UTC by dotdot0

### PR Description
Added Support for >>, <<, >>= and <<= Tokens

### Related Issue
Solves:
#54 
#55 

### Checklist
- [x] Have you added the necessary tests?
- [x] Only modified the files mentioned in the related issue(s)?
- [x] Are all tests passing?

2024-08-23 17:22 UTC, dotdot0 commented
Accidentally created a new branch from the branch of my prev PR that's why those changes are there.

2024-08-24 11:53 UTC, samthakur587 commented
hii @dotdot0 can you please resolve the merge conflicts

2024-08-24 11:55 UTC, samthakur587 requested changes

2024-08-24 11:55 UTC, samthakur587 commented on crosstl/src/translator/lexer.py
>      ("IF", r"\bif\b"),
these are bitwise left and right shift already added not the part of your task. the Assignment left and right shift is only in your task .

2024-08-28 06:41 UTC, samthakur587 approved these changes
hii @dotdot0 great work everything LGTM 🚀

2024-08-28 06:42 UTC, merged