Feat/assign operator parsing
CrossGL/crosstl pull request #98
Opened 2024-08-25 10:36 UTC by ArchitGupta07

```markdown
### PR Description
- Updated parser.py to handle Assignment AND, Assignment OR, Assignment XOR and Assignment Modulus.
- Added Testcases to validate the parser.

### Related Issue
This PR addresses and closes the following Issues:
-Closes #76  Add Parsing for Assignment AND Token
-Closes #77 Add Parsing for Assignment OR Token
-Closes #78  Add Parsing for Assignment XOR Token
-Closes #79 Add Parsing for Assignment Modulus Token

### Checklist
- [x] Have you added the necessary tests?
- [x] Only modified the files mentioned in the related issue(s)?
- [x] Are all tests passing?

```

2024-08-27 06:00 UTC, ArchitGupta07 commented
Updated PR description

2024-08-28 06:56 UTC, samthakur587 commented
hii @ArchitGupta07  can you please resolve the merge conflict

2024-08-28 06:57 UTC, samthakur587 requested changes
can you please resolve merge conflict

2024-08-28 08:21 UTC, ArchitGupta07 commented
Resolved the merge conflict

2024-08-28 09:41 UTC, samthakur587 requested changes

2024-08-28 09:41 UTC, samthakur587 commented on tests/test_translator/test_parser.py
> +            fragColor += vec4(1.0, 1.0, 0.0, 1.0) * isLightOn;
hii @ArchitGupta07 can you please write a new test function for your changes. don't rename and merge your changes in existing test function. can you please write a new function in your test file.

2024-08-28 10:06 UTC, ArchitGupta07 commented on tests/test_translator/test_parser.py
> +            fragColor += vec4(1.0, 1.0, 0.0, 1.0) * isLightOn;
Sorry for the inconvenience. I am new to this and got into some misunderstandings. I will make the necessary changes.

2024-08-29 08:36 UTC, samthakur587 commented
hii @ArchitGupta07 can you please resolve the merge conflicts

2024-08-30 03:42 UTC, ArchitGupta07 commented
Resolved the merge conflicts

2024-09-05 07:25 UTC, samthakur587 approved these changes
hii @ArchitGupta07 everything LGTM 🚀 

thanks for contribution

2024-09-05 07:26 UTC, merged